### ISSUE TITLE
image versions is out of date

### ISSUE THREAD

**Issue by krocos** [romnn/testcontainers#9]
For example: kafka is on version 5+ (`Image: "confluentinc/cp-kafka:5.5.3",`)

Current kafka version is 7.0.1

**Comment by romnn** [comment]
Dear @krocos, thanks for your contribution.

Excuse the late follow up, I have not been actively working on this. I just updated the dependencies and refactored the code.
All images are fixed to known-to-work versions in the tests, but use the `latest` tag otherwise. It is now also possible to specify the tag yourself. See the `examples` or `README.md` for more details

Best, Roman
